title: Danny Guo
email: dannyguo91@gmail.com
description: Danny Guo's personal website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dannyguo.com"
twitter_username: dannyguo
github_username:  dguo

permalink: /blog/:title/

# Build settings
markdown: kramdown
