version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Build the site
          command: jekyll build
