version: 2
jobs:
  build:
    docker:
      - image: jekyll/jekyll:pages
    working_directory: /srv/jekyll
    steps:
      - checkout
      - run:
          name: Build the site
          command: jekyll build
