version: 2
jobs:
  build:
    docker:
      - image: jguyomard/hugo-builder:0.40
    working_directory: /src
    steps:
      - checkout
      - run:
          name: Build the site
          command: hugo
